package @PACKAGE@;

import dalma.Description;
import dalma.Engine;
import dalma.Program;
import dalma.Resource;

@Description("This is a workflow application generated by Maven. Replace this with a human-readable description of this application")
public class Main extends Program {
    @Resource(description="@Resource indicates that this resource needs to be configured by the user.",optional=true)
    public String name = "(unconfigured)";

    @Override
    public void main(Engine engine) throws Exception {
        System.out.println("Running");
        if(engine.getConversations().isEmpty()) {
            for( int i=0; i<10; i++ )
                engine.createConversation(new ConversationImpl());
        }
    }
}